namespace ISOCodex.Countries;

internal static class CountrySeedData
{
    public static IReadOnlyList<CountryInfo> Countries { get; } = new List<CountryInfo>
    {
        new(
            CountryAlpha2Code.Parse("AD"),
            CountryAlpha3Code.Parse("AND"),
            CountryNumericCode.Parse("020"),
            "Andorra",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AE"),
            CountryAlpha3Code.Parse("ARE"),
            CountryNumericCode.Parse("784"),
            "United Arab Emirates",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AF"),
            CountryAlpha3Code.Parse("AFG"),
            CountryNumericCode.Parse("004"),
            "Afghanistan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AG"),
            CountryAlpha3Code.Parse("ATG"),
            CountryNumericCode.Parse("028"),
            "Antigua & Barbuda",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AI"),
            CountryAlpha3Code.Parse("AIA"),
            CountryNumericCode.Parse("660"),
            "Anguilla",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AL"),
            CountryAlpha3Code.Parse("ALB"),
            CountryNumericCode.Parse("008"),
            "Albania",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AM"),
            CountryAlpha3Code.Parse("ARM"),
            CountryNumericCode.Parse("051"),
            "Armenia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AO"),
            CountryAlpha3Code.Parse("AGO"),
            CountryNumericCode.Parse("024"),
            "Angola",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AQ"),
            CountryAlpha3Code.Parse("ATA"),
            CountryNumericCode.Parse("010"),
            "Antarctica",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AR"),
            CountryAlpha3Code.Parse("ARG"),
            CountryNumericCode.Parse("032"),
            "Argentina",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AS"),
            CountryAlpha3Code.Parse("ASM"),
            CountryNumericCode.Parse("016"),
            "American Samoa",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AT"),
            CountryAlpha3Code.Parse("AUT"),
            CountryNumericCode.Parse("040"),
            "Austria",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AU"),
            CountryAlpha3Code.Parse("AUS"),
            CountryNumericCode.Parse("036"),
            "Australia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AW"),
            CountryAlpha3Code.Parse("ABW"),
            CountryNumericCode.Parse("533"),
            "Aruba",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AX"),
            CountryAlpha3Code.Parse("ALA"),
            CountryNumericCode.Parse("248"),
            "Åland Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("AZ"),
            CountryAlpha3Code.Parse("AZE"),
            CountryNumericCode.Parse("031"),
            "Azerbaijan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BA"),
            CountryAlpha3Code.Parse("BIH"),
            CountryNumericCode.Parse("070"),
            "Bosnia & Herzegovina",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BB"),
            CountryAlpha3Code.Parse("BRB"),
            CountryNumericCode.Parse("052"),
            "Barbados",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BD"),
            CountryAlpha3Code.Parse("BGD"),
            CountryNumericCode.Parse("050"),
            "Bangladesh",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BE"),
            CountryAlpha3Code.Parse("BEL"),
            CountryNumericCode.Parse("056"),
            "Belgium",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BF"),
            CountryAlpha3Code.Parse("BFA"),
            CountryNumericCode.Parse("854"),
            "Burkina Faso",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BG"),
            CountryAlpha3Code.Parse("BGR"),
            CountryNumericCode.Parse("100"),
            "Bulgaria",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BH"),
            CountryAlpha3Code.Parse("BHR"),
            CountryNumericCode.Parse("048"),
            "Bahrain",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BI"),
            CountryAlpha3Code.Parse("BDI"),
            CountryNumericCode.Parse("108"),
            "Burundi",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BJ"),
            CountryAlpha3Code.Parse("BEN"),
            CountryNumericCode.Parse("204"),
            "Benin",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BL"),
            CountryAlpha3Code.Parse("BLM"),
            CountryNumericCode.Parse("652"),
            "St. Barthélemy",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BM"),
            CountryAlpha3Code.Parse("BMU"),
            CountryNumericCode.Parse("060"),
            "Bermuda",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BN"),
            CountryAlpha3Code.Parse("BRN"),
            CountryNumericCode.Parse("096"),
            "Brunei",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BO"),
            CountryAlpha3Code.Parse("BOL"),
            CountryNumericCode.Parse("068"),
            "Bolivia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BQ"),
            CountryAlpha3Code.Parse("BES"),
            CountryNumericCode.Parse("535"),
            "Caribbean Netherlands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BR"),
            CountryAlpha3Code.Parse("BRA"),
            CountryNumericCode.Parse("076"),
            "Brazil",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BS"),
            CountryAlpha3Code.Parse("BHS"),
            CountryNumericCode.Parse("044"),
            "Bahamas",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BT"),
            CountryAlpha3Code.Parse("BTN"),
            CountryNumericCode.Parse("064"),
            "Bhutan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BV"),
            CountryAlpha3Code.Parse("BVT"),
            CountryNumericCode.Parse("074"),
            "Bouvet Island",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BW"),
            CountryAlpha3Code.Parse("BWA"),
            CountryNumericCode.Parse("072"),
            "Botswana",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BY"),
            CountryAlpha3Code.Parse("BLR"),
            CountryNumericCode.Parse("112"),
            "Belarus",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("BZ"),
            CountryAlpha3Code.Parse("BLZ"),
            CountryNumericCode.Parse("084"),
            "Belize",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CA"),
            CountryAlpha3Code.Parse("CAN"),
            CountryNumericCode.Parse("124"),
            "Canada",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CC"),
            CountryAlpha3Code.Parse("CCK"),
            CountryNumericCode.Parse("166"),
            "Cocos (Keeling) Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CD"),
            CountryAlpha3Code.Parse("COD"),
            CountryNumericCode.Parse("180"),
            "Congo - Kinshasa",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CF"),
            CountryAlpha3Code.Parse("CAF"),
            CountryNumericCode.Parse("140"),
            "Central African Republic",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CG"),
            CountryAlpha3Code.Parse("COG"),
            CountryNumericCode.Parse("178"),
            "Congo - Brazzaville",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CH"),
            CountryAlpha3Code.Parse("CHE"),
            CountryNumericCode.Parse("756"),
            "Switzerland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CI"),
            CountryAlpha3Code.Parse("CIV"),
            CountryNumericCode.Parse("384"),
            "Côte d’Ivoire",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CK"),
            CountryAlpha3Code.Parse("COK"),
            CountryNumericCode.Parse("184"),
            "Cook Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CL"),
            CountryAlpha3Code.Parse("CHL"),
            CountryNumericCode.Parse("152"),
            "Chile",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CM"),
            CountryAlpha3Code.Parse("CMR"),
            CountryNumericCode.Parse("120"),
            "Cameroon",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CN"),
            CountryAlpha3Code.Parse("CHN"),
            CountryNumericCode.Parse("156"),
            "China",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CO"),
            CountryAlpha3Code.Parse("COL"),
            CountryNumericCode.Parse("170"),
            "Colombia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CR"),
            CountryAlpha3Code.Parse("CRI"),
            CountryNumericCode.Parse("188"),
            "Costa Rica",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CU"),
            CountryAlpha3Code.Parse("CUB"),
            CountryNumericCode.Parse("192"),
            "Cuba",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CV"),
            CountryAlpha3Code.Parse("CPV"),
            CountryNumericCode.Parse("132"),
            "Cape Verde",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CW"),
            CountryAlpha3Code.Parse("CUW"),
            CountryNumericCode.Parse("531"),
            "Curaçao",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CX"),
            CountryAlpha3Code.Parse("CXR"),
            CountryNumericCode.Parse("162"),
            "Christmas Island",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CY"),
            CountryAlpha3Code.Parse("CYP"),
            CountryNumericCode.Parse("196"),
            "Cyprus",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("CZ"),
            CountryAlpha3Code.Parse("CZE"),
            CountryNumericCode.Parse("203"),
            "Czechia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DE"),
            CountryAlpha3Code.Parse("DEU"),
            CountryNumericCode.Parse("276"),
            "Germany",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DJ"),
            CountryAlpha3Code.Parse("DJI"),
            CountryNumericCode.Parse("262"),
            "Djibouti",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DK"),
            CountryAlpha3Code.Parse("DNK"),
            CountryNumericCode.Parse("208"),
            "Denmark",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DM"),
            CountryAlpha3Code.Parse("DMA"),
            CountryNumericCode.Parse("212"),
            "Dominica",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DO"),
            CountryAlpha3Code.Parse("DOM"),
            CountryNumericCode.Parse("214"),
            "Dominican Republic",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("DZ"),
            CountryAlpha3Code.Parse("DZA"),
            CountryNumericCode.Parse("012"),
            "Algeria",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("EC"),
            CountryAlpha3Code.Parse("ECU"),
            CountryNumericCode.Parse("218"),
            "Ecuador",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("EE"),
            CountryAlpha3Code.Parse("EST"),
            CountryNumericCode.Parse("233"),
            "Estonia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("EG"),
            CountryAlpha3Code.Parse("EGY"),
            CountryNumericCode.Parse("818"),
            "Egypt",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("EH"),
            CountryAlpha3Code.Parse("ESH"),
            CountryNumericCode.Parse("732"),
            "Western Sahara",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ER"),
            CountryAlpha3Code.Parse("ERI"),
            CountryNumericCode.Parse("232"),
            "Eritrea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ES"),
            CountryAlpha3Code.Parse("ESP"),
            CountryNumericCode.Parse("724"),
            "Spain",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ET"),
            CountryAlpha3Code.Parse("ETH"),
            CountryNumericCode.Parse("231"),
            "Ethiopia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FI"),
            CountryAlpha3Code.Parse("FIN"),
            CountryNumericCode.Parse("246"),
            "Finland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FJ"),
            CountryAlpha3Code.Parse("FJI"),
            CountryNumericCode.Parse("242"),
            "Fiji",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FK"),
            CountryAlpha3Code.Parse("FLK"),
            CountryNumericCode.Parse("238"),
            "Falkland Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FM"),
            CountryAlpha3Code.Parse("FSM"),
            CountryNumericCode.Parse("583"),
            "Micronesia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FO"),
            CountryAlpha3Code.Parse("FRO"),
            CountryNumericCode.Parse("234"),
            "Faroe Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("FR"),
            CountryAlpha3Code.Parse("FRA"),
            CountryNumericCode.Parse("250"),
            "France",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GA"),
            CountryAlpha3Code.Parse("GAB"),
            CountryNumericCode.Parse("266"),
            "Gabon",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GB"),
            CountryAlpha3Code.Parse("GBR"),
            CountryNumericCode.Parse("826"),
            "United Kingdom",
            null,
            CountryEntryStatus.Current,
            commonAliases: new[] { "Britain", "Great Britain" },
            notes: new[] { "GB is the canonical ISO-style alpha-2 country code used by this package.", "UK is commonly encountered but is not silently treated as canonical GB." }),
        new(
            CountryAlpha2Code.Parse("GD"),
            CountryAlpha3Code.Parse("GRD"),
            CountryNumericCode.Parse("308"),
            "Grenada",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GE"),
            CountryAlpha3Code.Parse("GEO"),
            CountryNumericCode.Parse("268"),
            "Georgia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GF"),
            CountryAlpha3Code.Parse("GUF"),
            CountryNumericCode.Parse("254"),
            "French Guiana",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GG"),
            CountryAlpha3Code.Parse("GGY"),
            CountryNumericCode.Parse("831"),
            "Guernsey",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GH"),
            CountryAlpha3Code.Parse("GHA"),
            CountryNumericCode.Parse("288"),
            "Ghana",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GI"),
            CountryAlpha3Code.Parse("GIB"),
            CountryNumericCode.Parse("292"),
            "Gibraltar",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GL"),
            CountryAlpha3Code.Parse("GRL"),
            CountryNumericCode.Parse("304"),
            "Greenland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GM"),
            CountryAlpha3Code.Parse("GMB"),
            CountryNumericCode.Parse("270"),
            "Gambia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GN"),
            CountryAlpha3Code.Parse("GIN"),
            CountryNumericCode.Parse("324"),
            "Guinea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GP"),
            CountryAlpha3Code.Parse("GLP"),
            CountryNumericCode.Parse("312"),
            "Guadeloupe",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GQ"),
            CountryAlpha3Code.Parse("GNQ"),
            CountryNumericCode.Parse("226"),
            "Equatorial Guinea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GR"),
            CountryAlpha3Code.Parse("GRC"),
            CountryNumericCode.Parse("300"),
            "Greece",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GS"),
            CountryAlpha3Code.Parse("SGS"),
            CountryNumericCode.Parse("239"),
            "South Georgia & South Sandwich Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GT"),
            CountryAlpha3Code.Parse("GTM"),
            CountryNumericCode.Parse("320"),
            "Guatemala",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GU"),
            CountryAlpha3Code.Parse("GUM"),
            CountryNumericCode.Parse("316"),
            "Guam",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GW"),
            CountryAlpha3Code.Parse("GNB"),
            CountryNumericCode.Parse("624"),
            "Guinea-Bissau",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("GY"),
            CountryAlpha3Code.Parse("GUY"),
            CountryNumericCode.Parse("328"),
            "Guyana",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HK"),
            CountryAlpha3Code.Parse("HKG"),
            CountryNumericCode.Parse("344"),
            "Hong Kong SAR China",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HM"),
            CountryAlpha3Code.Parse("HMD"),
            CountryNumericCode.Parse("334"),
            "Heard & McDonald Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HN"),
            CountryAlpha3Code.Parse("HND"),
            CountryNumericCode.Parse("340"),
            "Honduras",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HR"),
            CountryAlpha3Code.Parse("HRV"),
            CountryNumericCode.Parse("191"),
            "Croatia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HT"),
            CountryAlpha3Code.Parse("HTI"),
            CountryNumericCode.Parse("332"),
            "Haiti",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("HU"),
            CountryAlpha3Code.Parse("HUN"),
            CountryNumericCode.Parse("348"),
            "Hungary",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ID"),
            CountryAlpha3Code.Parse("IDN"),
            CountryNumericCode.Parse("360"),
            "Indonesia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IE"),
            CountryAlpha3Code.Parse("IRL"),
            CountryNumericCode.Parse("372"),
            "Ireland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IL"),
            CountryAlpha3Code.Parse("ISR"),
            CountryNumericCode.Parse("376"),
            "Israel",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IM"),
            CountryAlpha3Code.Parse("IMN"),
            CountryNumericCode.Parse("833"),
            "Isle of Man",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IN"),
            CountryAlpha3Code.Parse("IND"),
            CountryNumericCode.Parse("356"),
            "India",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IO"),
            CountryAlpha3Code.Parse("IOT"),
            CountryNumericCode.Parse("086"),
            "British Indian Ocean Territory",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IQ"),
            CountryAlpha3Code.Parse("IRQ"),
            CountryNumericCode.Parse("368"),
            "Iraq",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IR"),
            CountryAlpha3Code.Parse("IRN"),
            CountryNumericCode.Parse("364"),
            "Iran",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IS"),
            CountryAlpha3Code.Parse("ISL"),
            CountryNumericCode.Parse("352"),
            "Iceland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("IT"),
            CountryAlpha3Code.Parse("ITA"),
            CountryNumericCode.Parse("380"),
            "Italy",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("JE"),
            CountryAlpha3Code.Parse("JEY"),
            CountryNumericCode.Parse("832"),
            "Jersey",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("JM"),
            CountryAlpha3Code.Parse("JAM"),
            CountryNumericCode.Parse("388"),
            "Jamaica",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("JO"),
            CountryAlpha3Code.Parse("JOR"),
            CountryNumericCode.Parse("400"),
            "Jordan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("JP"),
            CountryAlpha3Code.Parse("JPN"),
            CountryNumericCode.Parse("392"),
            "Japan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KE"),
            CountryAlpha3Code.Parse("KEN"),
            CountryNumericCode.Parse("404"),
            "Kenya",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KG"),
            CountryAlpha3Code.Parse("KGZ"),
            CountryNumericCode.Parse("417"),
            "Kyrgyzstan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KH"),
            CountryAlpha3Code.Parse("KHM"),
            CountryNumericCode.Parse("116"),
            "Cambodia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KI"),
            CountryAlpha3Code.Parse("KIR"),
            CountryNumericCode.Parse("296"),
            "Kiribati",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KM"),
            CountryAlpha3Code.Parse("COM"),
            CountryNumericCode.Parse("174"),
            "Comoros",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KN"),
            CountryAlpha3Code.Parse("KNA"),
            CountryNumericCode.Parse("659"),
            "St. Kitts & Nevis",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KP"),
            CountryAlpha3Code.Parse("PRK"),
            CountryNumericCode.Parse("408"),
            "North Korea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KR"),
            CountryAlpha3Code.Parse("KOR"),
            CountryNumericCode.Parse("410"),
            "South Korea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KW"),
            CountryAlpha3Code.Parse("KWT"),
            CountryNumericCode.Parse("414"),
            "Kuwait",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KY"),
            CountryAlpha3Code.Parse("CYM"),
            CountryNumericCode.Parse("136"),
            "Cayman Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("KZ"),
            CountryAlpha3Code.Parse("KAZ"),
            CountryNumericCode.Parse("398"),
            "Kazakhstan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LA"),
            CountryAlpha3Code.Parse("LAO"),
            CountryNumericCode.Parse("418"),
            "Laos",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LB"),
            CountryAlpha3Code.Parse("LBN"),
            CountryNumericCode.Parse("422"),
            "Lebanon",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LC"),
            CountryAlpha3Code.Parse("LCA"),
            CountryNumericCode.Parse("662"),
            "St. Lucia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LI"),
            CountryAlpha3Code.Parse("LIE"),
            CountryNumericCode.Parse("438"),
            "Liechtenstein",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LK"),
            CountryAlpha3Code.Parse("LKA"),
            CountryNumericCode.Parse("144"),
            "Sri Lanka",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LR"),
            CountryAlpha3Code.Parse("LBR"),
            CountryNumericCode.Parse("430"),
            "Liberia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LS"),
            CountryAlpha3Code.Parse("LSO"),
            CountryNumericCode.Parse("426"),
            "Lesotho",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LT"),
            CountryAlpha3Code.Parse("LTU"),
            CountryNumericCode.Parse("440"),
            "Lithuania",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LU"),
            CountryAlpha3Code.Parse("LUX"),
            CountryNumericCode.Parse("442"),
            "Luxembourg",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LV"),
            CountryAlpha3Code.Parse("LVA"),
            CountryNumericCode.Parse("428"),
            "Latvia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("LY"),
            CountryAlpha3Code.Parse("LBY"),
            CountryNumericCode.Parse("434"),
            "Libya",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MA"),
            CountryAlpha3Code.Parse("MAR"),
            CountryNumericCode.Parse("504"),
            "Morocco",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MC"),
            CountryAlpha3Code.Parse("MCO"),
            CountryNumericCode.Parse("492"),
            "Monaco",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MD"),
            CountryAlpha3Code.Parse("MDA"),
            CountryNumericCode.Parse("498"),
            "Moldova",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ME"),
            CountryAlpha3Code.Parse("MNE"),
            CountryNumericCode.Parse("499"),
            "Montenegro",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MF"),
            CountryAlpha3Code.Parse("MAF"),
            CountryNumericCode.Parse("663"),
            "St. Martin",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MG"),
            CountryAlpha3Code.Parse("MDG"),
            CountryNumericCode.Parse("450"),
            "Madagascar",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MH"),
            CountryAlpha3Code.Parse("MHL"),
            CountryNumericCode.Parse("584"),
            "Marshall Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MK"),
            CountryAlpha3Code.Parse("MKD"),
            CountryNumericCode.Parse("807"),
            "North Macedonia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ML"),
            CountryAlpha3Code.Parse("MLI"),
            CountryNumericCode.Parse("466"),
            "Mali",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MM"),
            CountryAlpha3Code.Parse("MMR"),
            CountryNumericCode.Parse("104"),
            "Myanmar (Burma)",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MN"),
            CountryAlpha3Code.Parse("MNG"),
            CountryNumericCode.Parse("496"),
            "Mongolia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MO"),
            CountryAlpha3Code.Parse("MAC"),
            CountryNumericCode.Parse("446"),
            "Macao SAR China",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MP"),
            CountryAlpha3Code.Parse("MNP"),
            CountryNumericCode.Parse("580"),
            "Northern Mariana Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MQ"),
            CountryAlpha3Code.Parse("MTQ"),
            CountryNumericCode.Parse("474"),
            "Martinique",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MR"),
            CountryAlpha3Code.Parse("MRT"),
            CountryNumericCode.Parse("478"),
            "Mauritania",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MS"),
            CountryAlpha3Code.Parse("MSR"),
            CountryNumericCode.Parse("500"),
            "Montserrat",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MT"),
            CountryAlpha3Code.Parse("MLT"),
            CountryNumericCode.Parse("470"),
            "Malta",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MU"),
            CountryAlpha3Code.Parse("MUS"),
            CountryNumericCode.Parse("480"),
            "Mauritius",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MV"),
            CountryAlpha3Code.Parse("MDV"),
            CountryNumericCode.Parse("462"),
            "Maldives",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MW"),
            CountryAlpha3Code.Parse("MWI"),
            CountryNumericCode.Parse("454"),
            "Malawi",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MX"),
            CountryAlpha3Code.Parse("MEX"),
            CountryNumericCode.Parse("484"),
            "Mexico",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MY"),
            CountryAlpha3Code.Parse("MYS"),
            CountryNumericCode.Parse("458"),
            "Malaysia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("MZ"),
            CountryAlpha3Code.Parse("MOZ"),
            CountryNumericCode.Parse("508"),
            "Mozambique",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NA"),
            CountryAlpha3Code.Parse("NAM"),
            CountryNumericCode.Parse("516"),
            "Namibia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NC"),
            CountryAlpha3Code.Parse("NCL"),
            CountryNumericCode.Parse("540"),
            "New Caledonia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NE"),
            CountryAlpha3Code.Parse("NER"),
            CountryNumericCode.Parse("562"),
            "Niger",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NF"),
            CountryAlpha3Code.Parse("NFK"),
            CountryNumericCode.Parse("574"),
            "Norfolk Island",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NG"),
            CountryAlpha3Code.Parse("NGA"),
            CountryNumericCode.Parse("566"),
            "Nigeria",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NI"),
            CountryAlpha3Code.Parse("NIC"),
            CountryNumericCode.Parse("558"),
            "Nicaragua",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NL"),
            CountryAlpha3Code.Parse("NLD"),
            CountryNumericCode.Parse("528"),
            "Netherlands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NO"),
            CountryAlpha3Code.Parse("NOR"),
            CountryNumericCode.Parse("578"),
            "Norway",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NP"),
            CountryAlpha3Code.Parse("NPL"),
            CountryNumericCode.Parse("524"),
            "Nepal",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NR"),
            CountryAlpha3Code.Parse("NRU"),
            CountryNumericCode.Parse("520"),
            "Nauru",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NU"),
            CountryAlpha3Code.Parse("NIU"),
            CountryNumericCode.Parse("570"),
            "Niue",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("NZ"),
            CountryAlpha3Code.Parse("NZL"),
            CountryNumericCode.Parse("554"),
            "New Zealand",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("OM"),
            CountryAlpha3Code.Parse("OMN"),
            CountryNumericCode.Parse("512"),
            "Oman",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PA"),
            CountryAlpha3Code.Parse("PAN"),
            CountryNumericCode.Parse("591"),
            "Panama",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PE"),
            CountryAlpha3Code.Parse("PER"),
            CountryNumericCode.Parse("604"),
            "Peru",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PF"),
            CountryAlpha3Code.Parse("PYF"),
            CountryNumericCode.Parse("258"),
            "French Polynesia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PG"),
            CountryAlpha3Code.Parse("PNG"),
            CountryNumericCode.Parse("598"),
            "Papua New Guinea",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PH"),
            CountryAlpha3Code.Parse("PHL"),
            CountryNumericCode.Parse("608"),
            "Philippines",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PK"),
            CountryAlpha3Code.Parse("PAK"),
            CountryNumericCode.Parse("586"),
            "Pakistan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PL"),
            CountryAlpha3Code.Parse("POL"),
            CountryNumericCode.Parse("616"),
            "Poland",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PM"),
            CountryAlpha3Code.Parse("SPM"),
            CountryNumericCode.Parse("666"),
            "St. Pierre & Miquelon",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PN"),
            CountryAlpha3Code.Parse("PCN"),
            CountryNumericCode.Parse("612"),
            "Pitcairn Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PR"),
            CountryAlpha3Code.Parse("PRI"),
            CountryNumericCode.Parse("630"),
            "Puerto Rico",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PS"),
            CountryAlpha3Code.Parse("PSE"),
            CountryNumericCode.Parse("275"),
            "Palestinian Territories",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PT"),
            CountryAlpha3Code.Parse("PRT"),
            CountryNumericCode.Parse("620"),
            "Portugal",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PW"),
            CountryAlpha3Code.Parse("PLW"),
            CountryNumericCode.Parse("585"),
            "Palau",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("PY"),
            CountryAlpha3Code.Parse("PRY"),
            CountryNumericCode.Parse("600"),
            "Paraguay",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("QA"),
            CountryAlpha3Code.Parse("QAT"),
            CountryNumericCode.Parse("634"),
            "Qatar",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("RE"),
            CountryAlpha3Code.Parse("REU"),
            CountryNumericCode.Parse("638"),
            "Réunion",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("RO"),
            CountryAlpha3Code.Parse("ROU"),
            CountryNumericCode.Parse("642"),
            "Romania",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("RS"),
            CountryAlpha3Code.Parse("SRB"),
            CountryNumericCode.Parse("688"),
            "Serbia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("RU"),
            CountryAlpha3Code.Parse("RUS"),
            CountryNumericCode.Parse("643"),
            "Russia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("RW"),
            CountryAlpha3Code.Parse("RWA"),
            CountryNumericCode.Parse("646"),
            "Rwanda",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SA"),
            CountryAlpha3Code.Parse("SAU"),
            CountryNumericCode.Parse("682"),
            "Saudi Arabia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SB"),
            CountryAlpha3Code.Parse("SLB"),
            CountryNumericCode.Parse("090"),
            "Solomon Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SC"),
            CountryAlpha3Code.Parse("SYC"),
            CountryNumericCode.Parse("690"),
            "Seychelles",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SD"),
            CountryAlpha3Code.Parse("SDN"),
            CountryNumericCode.Parse("729"),
            "Sudan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SE"),
            CountryAlpha3Code.Parse("SWE"),
            CountryNumericCode.Parse("752"),
            "Sweden",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SG"),
            CountryAlpha3Code.Parse("SGP"),
            CountryNumericCode.Parse("702"),
            "Singapore",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SH"),
            CountryAlpha3Code.Parse("SHN"),
            CountryNumericCode.Parse("654"),
            "St. Helena",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SI"),
            CountryAlpha3Code.Parse("SVN"),
            CountryNumericCode.Parse("705"),
            "Slovenia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SJ"),
            CountryAlpha3Code.Parse("SJM"),
            CountryNumericCode.Parse("744"),
            "Svalbard & Jan Mayen",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SK"),
            CountryAlpha3Code.Parse("SVK"),
            CountryNumericCode.Parse("703"),
            "Slovakia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SL"),
            CountryAlpha3Code.Parse("SLE"),
            CountryNumericCode.Parse("694"),
            "Sierra Leone",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SM"),
            CountryAlpha3Code.Parse("SMR"),
            CountryNumericCode.Parse("674"),
            "San Marino",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SN"),
            CountryAlpha3Code.Parse("SEN"),
            CountryNumericCode.Parse("686"),
            "Senegal",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SO"),
            CountryAlpha3Code.Parse("SOM"),
            CountryNumericCode.Parse("706"),
            "Somalia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SR"),
            CountryAlpha3Code.Parse("SUR"),
            CountryNumericCode.Parse("740"),
            "Suriname",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SS"),
            CountryAlpha3Code.Parse("SSD"),
            CountryNumericCode.Parse("728"),
            "South Sudan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ST"),
            CountryAlpha3Code.Parse("STP"),
            CountryNumericCode.Parse("678"),
            "São Tomé & Príncipe",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SV"),
            CountryAlpha3Code.Parse("SLV"),
            CountryNumericCode.Parse("222"),
            "El Salvador",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SX"),
            CountryAlpha3Code.Parse("SXM"),
            CountryNumericCode.Parse("534"),
            "Sint Maarten",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SY"),
            CountryAlpha3Code.Parse("SYR"),
            CountryNumericCode.Parse("760"),
            "Syria",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("SZ"),
            CountryAlpha3Code.Parse("SWZ"),
            CountryNumericCode.Parse("748"),
            "Eswatini",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TC"),
            CountryAlpha3Code.Parse("TCA"),
            CountryNumericCode.Parse("796"),
            "Turks & Caicos Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TD"),
            CountryAlpha3Code.Parse("TCD"),
            CountryNumericCode.Parse("148"),
            "Chad",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TF"),
            CountryAlpha3Code.Parse("ATF"),
            CountryNumericCode.Parse("260"),
            "French Southern Territories",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TG"),
            CountryAlpha3Code.Parse("TGO"),
            CountryNumericCode.Parse("768"),
            "Togo",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TH"),
            CountryAlpha3Code.Parse("THA"),
            CountryNumericCode.Parse("764"),
            "Thailand",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TJ"),
            CountryAlpha3Code.Parse("TJK"),
            CountryNumericCode.Parse("762"),
            "Tajikistan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TK"),
            CountryAlpha3Code.Parse("TKL"),
            CountryNumericCode.Parse("772"),
            "Tokelau",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TL"),
            CountryAlpha3Code.Parse("TLS"),
            CountryNumericCode.Parse("626"),
            "Timor-Leste",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TM"),
            CountryAlpha3Code.Parse("TKM"),
            CountryNumericCode.Parse("795"),
            "Turkmenistan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TN"),
            CountryAlpha3Code.Parse("TUN"),
            CountryNumericCode.Parse("788"),
            "Tunisia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TO"),
            CountryAlpha3Code.Parse("TON"),
            CountryNumericCode.Parse("776"),
            "Tonga",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TR"),
            CountryAlpha3Code.Parse("TUR"),
            CountryNumericCode.Parse("792"),
            "Türkiye",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TT"),
            CountryAlpha3Code.Parse("TTO"),
            CountryNumericCode.Parse("780"),
            "Trinidad & Tobago",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TV"),
            CountryAlpha3Code.Parse("TUV"),
            CountryNumericCode.Parse("798"),
            "Tuvalu",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TW"),
            CountryAlpha3Code.Parse("TWN"),
            CountryNumericCode.Parse("158"),
            "Taiwan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("TZ"),
            CountryAlpha3Code.Parse("TZA"),
            CountryNumericCode.Parse("834"),
            "Tanzania",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("UA"),
            CountryAlpha3Code.Parse("UKR"),
            CountryNumericCode.Parse("804"),
            "Ukraine",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("UG"),
            CountryAlpha3Code.Parse("UGA"),
            CountryNumericCode.Parse("800"),
            "Uganda",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("UM"),
            CountryAlpha3Code.Parse("UMI"),
            CountryNumericCode.Parse("581"),
            "U.S. Outlying Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("US"),
            CountryAlpha3Code.Parse("USA"),
            CountryNumericCode.Parse("840"),
            "United States",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("UY"),
            CountryAlpha3Code.Parse("URY"),
            CountryNumericCode.Parse("858"),
            "Uruguay",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("UZ"),
            CountryAlpha3Code.Parse("UZB"),
            CountryNumericCode.Parse("860"),
            "Uzbekistan",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VA"),
            CountryAlpha3Code.Parse("VAT"),
            CountryNumericCode.Parse("336"),
            "Vatican City",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VC"),
            CountryAlpha3Code.Parse("VCT"),
            CountryNumericCode.Parse("670"),
            "St. Vincent & Grenadines",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VE"),
            CountryAlpha3Code.Parse("VEN"),
            CountryNumericCode.Parse("862"),
            "Venezuela",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VG"),
            CountryAlpha3Code.Parse("VGB"),
            CountryNumericCode.Parse("092"),
            "British Virgin Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VI"),
            CountryAlpha3Code.Parse("VIR"),
            CountryNumericCode.Parse("850"),
            "U.S. Virgin Islands",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VN"),
            CountryAlpha3Code.Parse("VNM"),
            CountryNumericCode.Parse("704"),
            "Vietnam",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("VU"),
            CountryAlpha3Code.Parse("VUT"),
            CountryNumericCode.Parse("548"),
            "Vanuatu",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("WF"),
            CountryAlpha3Code.Parse("WLF"),
            CountryNumericCode.Parse("876"),
            "Wallis & Futuna",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("WS"),
            CountryAlpha3Code.Parse("WSM"),
            CountryNumericCode.Parse("882"),
            "Samoa",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("YE"),
            CountryAlpha3Code.Parse("YEM"),
            CountryNumericCode.Parse("887"),
            "Yemen",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("YT"),
            CountryAlpha3Code.Parse("MYT"),
            CountryNumericCode.Parse("175"),
            "Mayotte",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ZA"),
            CountryAlpha3Code.Parse("ZAF"),
            CountryNumericCode.Parse("710"),
            "South Africa",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ZM"),
            CountryAlpha3Code.Parse("ZMB"),
            CountryNumericCode.Parse("894"),
            "Zambia",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null),
        new(
            CountryAlpha2Code.Parse("ZW"),
            CountryAlpha3Code.Parse("ZWE"),
            CountryNumericCode.Parse("716"),
            "Zimbabwe",
            null,
            CountryEntryStatus.Current,
            commonAliases: null,
            notes: null)
    }.AsReadOnly();

    public static IReadOnlyList<CountrySubdivisionInfo> Subdivisions { get; } = new List<CountrySubdivisionInfo>
    {
        new(CountrySubdivisionCode.Parse("AD-02"), CountryAlpha2Code.Parse("AD"), "Canillo", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-03"), CountryAlpha2Code.Parse("AD"), "Encamp", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-04"), CountryAlpha2Code.Parse("AD"), "La Massana", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-05"), CountryAlpha2Code.Parse("AD"), "Ordino", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-06"), CountryAlpha2Code.Parse("AD"), "Sant Julià de Lòria", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-07"), CountryAlpha2Code.Parse("AD"), "Andorra la Vella", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AD-08"), CountryAlpha2Code.Parse("AD"), "Escaldes-Engordany", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-AJ"), CountryAlpha2Code.Parse("AE"), "Ajman", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-AZ"), CountryAlpha2Code.Parse("AE"), "Abu Dhabi", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-DU"), CountryAlpha2Code.Parse("AE"), "Dubai", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-FU"), CountryAlpha2Code.Parse("AE"), "Fujairah", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-RK"), CountryAlpha2Code.Parse("AE"), "Ras al-Khaimah", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-SH"), CountryAlpha2Code.Parse("AE"), "Sharjah", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AE-UQ"), CountryAlpha2Code.Parse("AE"), "Umm al-Quwain", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-BAL"), CountryAlpha2Code.Parse("AF"), "Balkh", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-BAM"), CountryAlpha2Code.Parse("AF"), "Bamyan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-BDG"), CountryAlpha2Code.Parse("AF"), "Badghis", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-BDS"), CountryAlpha2Code.Parse("AF"), "Badakhshan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-BGL"), CountryAlpha2Code.Parse("AF"), "Baghlan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-DAY"), CountryAlpha2Code.Parse("AF"), "Daykundi", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-FRA"), CountryAlpha2Code.Parse("AF"), "Farah", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-FYB"), CountryAlpha2Code.Parse("AF"), "Faryab", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-GHA"), CountryAlpha2Code.Parse("AF"), "Ghazni", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-GHO"), CountryAlpha2Code.Parse("AF"), "Ghōr", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-HEL"), CountryAlpha2Code.Parse("AF"), "Helmand", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-HER"), CountryAlpha2Code.Parse("AF"), "Herat", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-JOW"), CountryAlpha2Code.Parse("AF"), "Jowzjan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KAB"), CountryAlpha2Code.Parse("AF"), "Kabul", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KAN"), CountryAlpha2Code.Parse("AF"), "Kandahar", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KAP"), CountryAlpha2Code.Parse("AF"), "Kapisa", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KDZ"), CountryAlpha2Code.Parse("AF"), "Kunduz", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KHO"), CountryAlpha2Code.Parse("AF"), "Khost", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-KNR"), CountryAlpha2Code.Parse("AF"), "Kunar", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-LAG"), CountryAlpha2Code.Parse("AF"), "Laghman", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-LOG"), CountryAlpha2Code.Parse("AF"), "Logar", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-NAN"), CountryAlpha2Code.Parse("AF"), "Nangarhar", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-NIM"), CountryAlpha2Code.Parse("AF"), "Nimruz", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-NUR"), CountryAlpha2Code.Parse("AF"), "Nuristan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-PAN"), CountryAlpha2Code.Parse("AF"), "Panjshir", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-PAR"), CountryAlpha2Code.Parse("AF"), "Parwan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-PIA"), CountryAlpha2Code.Parse("AF"), "Paktia", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-PKA"), CountryAlpha2Code.Parse("AF"), "Paktika", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-SAM"), CountryAlpha2Code.Parse("AF"), "Samangan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-SAR"), CountryAlpha2Code.Parse("AF"), "Sar-e Pol", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-TAK"), CountryAlpha2Code.Parse("AF"), "Takhar", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-URU"), CountryAlpha2Code.Parse("AF"), "Urozgan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-WAR"), CountryAlpha2Code.Parse("AF"), "Maidan Wardak", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AF-ZAB"), CountryAlpha2Code.Parse("AF"), "Zabul", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-03"), CountryAlpha2Code.Parse("AG"), "Saint George", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-04"), CountryAlpha2Code.Parse("AG"), "Saint John", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-05"), CountryAlpha2Code.Parse("AG"), "Saint Mary", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-06"), CountryAlpha2Code.Parse("AG"), "Saint Paul", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-07"), CountryAlpha2Code.Parse("AG"), "Saint Peter", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-08"), CountryAlpha2Code.Parse("AG"), "Saint Philip", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-10"), CountryAlpha2Code.Parse("AG"), "Barbuda", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AG-11"), CountryAlpha2Code.Parse("AG"), "Redonda", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-01"), CountryAlpha2Code.Parse("AL"), "Berat County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-02"), CountryAlpha2Code.Parse("AL"), "Durrës County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-03"), CountryAlpha2Code.Parse("AL"), "Elbasan County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-04"), CountryAlpha2Code.Parse("AL"), "Fier County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-05"), CountryAlpha2Code.Parse("AL"), "Gjirokastër County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-06"), CountryAlpha2Code.Parse("AL"), "Korçë County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-07"), CountryAlpha2Code.Parse("AL"), "Kukës County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-08"), CountryAlpha2Code.Parse("AL"), "Lezhë County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-09"), CountryAlpha2Code.Parse("AL"), "Dibër County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-10"), CountryAlpha2Code.Parse("AL"), "Shkodër County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-11"), CountryAlpha2Code.Parse("AL"), "Tirana County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AL-12"), CountryAlpha2Code.Parse("AL"), "Vlorë County", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-AG"), CountryAlpha2Code.Parse("AM"), "Aragatsotn", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-AR"), CountryAlpha2Code.Parse("AM"), "Ararat", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-AV"), CountryAlpha2Code.Parse("AM"), "Armavir", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-ER"), CountryAlpha2Code.Parse("AM"), "Yerevan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-GR"), CountryAlpha2Code.Parse("AM"), "Gegharkunik", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-KT"), CountryAlpha2Code.Parse("AM"), "Kotayk", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-LO"), CountryAlpha2Code.Parse("AM"), "Lori", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-SH"), CountryAlpha2Code.Parse("AM"), "Shirak", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-SU"), CountryAlpha2Code.Parse("AM"), "Syunik", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-TV"), CountryAlpha2Code.Parse("AM"), "Tavush", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AM-VD"), CountryAlpha2Code.Parse("AM"), "Vayots Dzor", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-BGO"), CountryAlpha2Code.Parse("AO"), "Bengo", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-BGU"), CountryAlpha2Code.Parse("AO"), "Benguela", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-BIE"), CountryAlpha2Code.Parse("AO"), "Bié", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-CAB"), CountryAlpha2Code.Parse("AO"), "Cabinda", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-CCU"), CountryAlpha2Code.Parse("AO"), "Cuando Cubango", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-CNN"), CountryAlpha2Code.Parse("AO"), "Cunene", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-CNO"), CountryAlpha2Code.Parse("AO"), "Cuanza Norte", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-CUS"), CountryAlpha2Code.Parse("AO"), "Cuanza Sul", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-HUA"), CountryAlpha2Code.Parse("AO"), "Huambo", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-HUI"), CountryAlpha2Code.Parse("AO"), "Huíla", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-LNO"), CountryAlpha2Code.Parse("AO"), "Lunda Norte", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-LSU"), CountryAlpha2Code.Parse("AO"), "Lunda Sul", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-LUA"), CountryAlpha2Code.Parse("AO"), "Luanda", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-MAL"), CountryAlpha2Code.Parse("AO"), "Malanje", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-MOX"), CountryAlpha2Code.Parse("AO"), "Moxico", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-NAM"), CountryAlpha2Code.Parse("AO"), "Namibe", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-UIG"), CountryAlpha2Code.Parse("AO"), "Uíge", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AO-ZAI"), CountryAlpha2Code.Parse("AO"), "Zaire", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-A"), CountryAlpha2Code.Parse("AR"), "Salta", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-B"), CountryAlpha2Code.Parse("AR"), "Buenos Aires Province", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-C"), CountryAlpha2Code.Parse("AR"), "Buenos Aires", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-D"), CountryAlpha2Code.Parse("AR"), "San Luis", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-E"), CountryAlpha2Code.Parse("AR"), "Entre Ríos", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-F"), CountryAlpha2Code.Parse("AR"), "La Rioja", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-G"), CountryAlpha2Code.Parse("AR"), "Santiago del Estero", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-H"), CountryAlpha2Code.Parse("AR"), "Chaco", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-J"), CountryAlpha2Code.Parse("AR"), "San Juan", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-K"), CountryAlpha2Code.Parse("AR"), "Catamarca", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-L"), CountryAlpha2Code.Parse("AR"), "La Pampa", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-M"), CountryAlpha2Code.Parse("AR"), "Mendoza", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-N"), CountryAlpha2Code.Parse("AR"), "Misiones", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-P"), CountryAlpha2Code.Parse("AR"), "Formosa", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-Q"), CountryAlpha2Code.Parse("AR"), "Neuquén", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-R"), CountryAlpha2Code.Parse("AR"), "Río Negro", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-S"), CountryAlpha2Code.Parse("AR"), "Santa Fe", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-T"), CountryAlpha2Code.Parse("AR"), "Tucumán", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-U"), CountryAlpha2Code.Parse("AR"), "Chubut", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-V"), CountryAlpha2Code.Parse("AR"), "Tierra del Fuego", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-W"), CountryAlpha2Code.Parse("AR"), "Corrientes", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-X"), CountryAlpha2Code.Parse("AR"), "Córdoba", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-Y"), CountryAlpha2Code.Parse("AR"), "Jujuy", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AR-Z"), CountryAlpha2Code.Parse("AR"), "Santa Cruz", null, CountrySubdivisionType.Unknown),
        new(CountrySubdivisionCode.Parse("AU-NSW"), CountryAlpha2Code.Parse("AU"), "New South Wales", null, CountrySubdivisionType.State),
        new(CountrySubdivisionCode.Parse("CA-ON"), CountryAlpha2Code.Parse("CA"), "Ontario", null, CountrySubdivisionType.Province),
        new(CountrySubdivisionCode.Parse("GB-ENG"), CountryAlpha2Code.Parse("GB"), "England", null, CountrySubdivisionType.Nation),
        new(CountrySubdivisionCode.Parse("GB-NIR"), CountryAlpha2Code.Parse("GB"), "Northern Ireland", null, CountrySubdivisionType.Nation),
        new(CountrySubdivisionCode.Parse("GB-SCT"), CountryAlpha2Code.Parse("GB"), "Scotland", null, CountrySubdivisionType.Nation),
        new(CountrySubdivisionCode.Parse("GB-WLS"), CountryAlpha2Code.Parse("GB"), "Wales", null, CountrySubdivisionType.Nation),
        new(CountrySubdivisionCode.Parse("IE-D"), CountryAlpha2Code.Parse("IE"), "Dublin", null, CountrySubdivisionType.County),
        new(CountrySubdivisionCode.Parse("US-CA"), CountryAlpha2Code.Parse("US"), "California", null, CountrySubdivisionType.State)
    }.AsReadOnly();
}

